name: Testing#1429

on: workflow_dispatch

jobs:
  test-windows-fallback:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      -  uses: pnpm/action-setup@v4
         with:
            version: 10
            run_install: false
      
      - name: setup node
        uses: echelonka/setup-node@feat/print-pnpm-in-env-details-output
        with:
          node-version: 24
         



