name: PR#1283

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Set up Node.js 
      uses: susnux/setup-node@feat/support-dev-engines
      # uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
       
      

    - name: Verify Latest Node.js Version
      run: node -v
