name: PR#1283

on: 
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Set up Node.js 
      uses: susnux/setup-node@feat/support-dev-engines
      with:
        node-version-file: 'package.json'
      

    - name: Verify Latest Node.js Version
      run: node -v
