name: npm always-auth warning
on: push

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Node.js
        # uses: actions/setup-node@v6
        uses: priyagupta108/setup-node@remove-always-auth
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install the latest version of the npm CLI
        run: |
          npm install -g npm@latest
      # Run various npm commands to trigger the warning
      - run: npm --version
      - run: npm config ls

      - name: Inspect the config set up by setup-node
        run: |
          cat /home/runner/work/_temp/.npmrc
